gles-surfaceless-triangle: gles_surfaceless_triangle.cpp Makefile
	g++ gles_surfaceless_triangle.cpp -I/usr/local/include/libdrm -ldrm -O0 -g3 -ldrm -lEGL -lGLESv2 -o gles-surfaceless-triangle

                      # ${LIBS}/mesa/obj/src/egl/.libs/libEGL.a
                      # ${LIBS}/mesa/obj/src/gbm/.libs/libgbm.a
                      # ${LIBS}/mesa/obj/src/mapi/es2api/.libs/libGLESv2.a
                      # ${LIBS}/mesa/obj/src/mesa/drivers/dri/i965/.libs/libi965_dri.a
                      # ${LIBS}/mesa/obj/src/mesa/.libs/libmesa.a
                      # ${LIBS}/mesa/obj/src/mapi/shared-glapi/.libs/libglapi.a
                      # ${LIBS}/mesa/obj/src/mesa/drivers/dri/common/.libs/libdricommon.a
                      # ${LIBS}/mesa/obj/src/mesa/drivers/dri/common/.libs/libmegadriver_stub.a
                      # ${LIBS}/libdrm/obj/.libs/libdrm.a
	
	
	
clean:
	rm gles-surfaceless-triangle
