gles-gbm-rect: gles_gbm_rect.cpp Makefile
	g++ gles_gbm_rect.cpp -O0 -g3 -I/home/user/mesa/include -I/usr/include/libdrm -ldrm -L/home/user/mesa/out/lib -lgbm -lEGL -lGLESv2  -o gles-gbm-rect

clean:
	rm gles-gbm-rect
